"""
SQLAlchemy 2.0 ORM models for the Prophet engine.

All 9 tables are defined here using ``Mapped[]`` type annotations and
:func:`mapped_column`.  JSONB columns use the SQLAlchemy ``JSON`` type which
maps to ``JSONB`` on PostgreSQL when paired with the asyncpg dialect.

Tables
------
1.  markets               — Discovered Polymarket weekly crypto markets
2.  orderbook_snapshots   — Periodic order-book captures per market / token
3.  observed_trades       — On-chain trades observed via CLOB API
4.  signals               — Trade signals generated by strategies
5.  paper_orders          — Simulated (paper) order lifecycle
6.  positions             — Aggregated open/closed positions + P&L
7.  price_snapshots       — BTC/ETH/SOL spot prices (1-min granularity)
8.  system_state          — Key/value store for runtime engine state
9.  strategy_configs      — Per-strategy, per-market parameter overrides
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from prophet.db.database import Base

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_NOW = func.now()  # Server-side default: current timestamp


def _utcnow() -> datetime:
    """Python-side UTC timestamp (used in default= where server default not preferred)."""
    from datetime import timezone

    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# 1. Markets
# ---------------------------------------------------------------------------


class Market(Base):
    """A Polymarket weekly crypto prediction market.

    Discovered by the :class:`~prophet.core.scanner.MarketScanner` and stored
    here as the central reference for all other tables.
    """

    __tablename__ = "markets"
    __table_args__ = (
        UniqueConstraint("condition_id", name="uq_markets_condition_id"),
        Index("ix_markets_crypto_status", "crypto", "status"),
        Index("ix_markets_resolution_date", "resolution_date"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    condition_id: Mapped[str] = mapped_column(
        String(255), nullable=False, unique=True, index=True,
        comment="Polymarket condition ID (hex string).",
    )
    question: Mapped[str] = mapped_column(
        String(1024), nullable=False,
        comment="Full question text as displayed on Polymarket.",
    )
    crypto: Mapped[str | None] = mapped_column(
        String(10), nullable=True,
        comment="Crypto symbol: BTC, ETH, SOL, or NULL for non-crypto markets.",
    )
    category: Mapped[str | None] = mapped_column(
        String(50), nullable=True, index=True,
        comment="Market category: crypto, sports, politics, entertainment, etc.",
    )
    threshold: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        comment="Price threshold parsed from question (e.g. 100000.0 for BTC above $100k).",
    )
    direction: Mapped[str | None] = mapped_column(
        String(10), nullable=True,
        comment="ABOVE or BELOW.",
    )
    resolution_date: Mapped[date | None] = mapped_column(
        Date, nullable=True,
        comment="Date (UTC) when the market resolves.",
    )
    token_id_yes: Mapped[str] = mapped_column(
        String(255), nullable=False,
        comment="CLOB token ID for the YES outcome.",
    )
    token_id_no: Mapped[str] = mapped_column(
        String(255), nullable=False,
        comment="CLOB token ID for the NO outcome.",
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="active", index=True,
        comment="Market lifecycle: active | resolved | expired.",
    )
    resolved_outcome: Mapped[str | None] = mapped_column(
        String(10), nullable=True,
        comment="Final outcome: YES or NO (set on resolution).",
    )
    resolution_time: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="Actual UTC timestamp when the market resolved.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW, onupdate=_NOW,
    )

    # Relationships
    snapshots: Mapped[list[OrderBookSnapshot]] = relationship(
        "OrderBookSnapshot", back_populates="market", lazy="selectin"
    )
    observed_trades: Mapped[list[ObservedTrade]] = relationship(
        "ObservedTrade", back_populates="market", lazy="selectin"
    )
    signals: Mapped[list[Signal]] = relationship(
        "Signal", back_populates="market", lazy="selectin"
    )
    paper_orders: Mapped[list[PaperOrder]] = relationship(
        "PaperOrder", back_populates="market", lazy="selectin"
    )
    positions: Mapped[list[Position]] = relationship(
        "Position", back_populates="market", lazy="selectin"
    )
    strategy_configs: Mapped[list[StrategyConfig]] = relationship(
        "StrategyConfig", back_populates="market", lazy="selectin"
    )

    def __repr__(self) -> str:
        return f"<Market id={self.id} crypto={self.crypto} status={self.status!r}>"


# ---------------------------------------------------------------------------
# 2. OrderBook Snapshots
# ---------------------------------------------------------------------------


class OrderBookSnapshot(Base):
    """Periodic capture of a Polymarket order book for a single token side.

    Snapshots are taken every 5 minutes for every active market.  The full
    bid/ask arrays are stored as JSONB (``raw_book``) alongside pre-computed
    metrics that are expensive to re-derive at query time.
    """

    __tablename__ = "orderbook_snapshots"
    __table_args__ = (
        Index("ix_obs_market_token_ts", "market_id", "token_id", "timestamp"),
        # timestamp index auto-created by index=True on column
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    market_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("markets.id", ondelete="CASCADE"), nullable=False, index=True,
    )
    token_id: Mapped[str] = mapped_column(
        String(255), nullable=False,
        comment="CLOB token ID (YES or NO side).",
    )
    side: Mapped[str] = mapped_column(
        String(5), nullable=False,
        comment="'yes' or 'no'.",
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True,
    )
    best_bid: Mapped[float | None] = mapped_column(Float, nullable=True)
    best_ask: Mapped[float | None] = mapped_column(Float, nullable=True)
    bid_depth_10pct: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0,
        comment="Total USD available within 10 % of the best bid.",
    )
    ask_depth_10pct: Mapped[float] = mapped_column(
        Float, nullable=False, default=0.0,
        comment="Total USD available within 10 % of the best ask.",
    )
    spread_pct: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        comment="(best_ask - best_bid) / best_ask * 100.",
    )
    raw_book: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict,
        comment="Full bid/ask arrays as returned by the CLOB API.",
    )

    # Relationships
    market: Mapped[Market] = relationship("Market", back_populates="snapshots")

    def __repr__(self) -> str:
        return (
            f"<OrderBookSnapshot id={self.id} market_id={self.market_id} "
            f"side={self.side!r} ts={self.timestamp}>"
        )


# ---------------------------------------------------------------------------
# 3. Observed Trades
# ---------------------------------------------------------------------------


class ObservedTrade(Base):
    """An on-chain trade observed via the CLOB trades API.

    Captured every 2 minutes.  Used as the authoritative signal for paper
    fill simulation: a paper order only fills when an actual trade occurs at
    or better than the target price.
    """

    __tablename__ = "observed_trades"
    __table_args__ = (
        Index("ix_ot_market_token_ts", "market_id", "token_id", "timestamp"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    market_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("markets.id", ondelete="CASCADE"), nullable=False, index=True,
    )
    token_id: Mapped[str] = mapped_column(String(255), nullable=False)
    side: Mapped[str] = mapped_column(
        String(5), nullable=False,
        comment="YES or NO.",
    )
    price: Mapped[float] = mapped_column(Float, nullable=False)
    size_usd: Mapped[float] = mapped_column(Float, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True,
    )
    maker: Mapped[str] = mapped_column(
        String(255), nullable=False, default="",
        comment="Maker wallet address (may be empty if not exposed by API).",
    )
    taker: Mapped[str] = mapped_column(
        String(255), nullable=False, default="",
        comment="Taker wallet address.",
    )

    # Relationships
    market: Mapped[Market] = relationship("Market", back_populates="observed_trades")

    def __repr__(self) -> str:
        return (
            f"<ObservedTrade id={self.id} market_id={self.market_id} "
            f"side={self.side!r} price={self.price} size={self.size_usd}>"
        )


# ---------------------------------------------------------------------------
# 4. Signals
# ---------------------------------------------------------------------------


class Signal(Base):
    """A trade signal produced by a strategy evaluation cycle.

    A signal expresses intent to place an order at a given price.  It is
    reviewed by the :class:`~prophet.core.risk_manager.RiskManager` before
    becoming a :class:`PaperOrder`.
    """

    __tablename__ = "signals"
    __table_args__ = (
        Index("ix_signals_market_strategy", "market_id", "strategy"),
        # status and created_at indexes are auto-created by index=True on columns
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    market_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("markets.id", ondelete="CASCADE"), nullable=False, index=True,
    )
    strategy: Mapped[str] = mapped_column(
        String(50), nullable=False,
        comment="Strategy name: volatility_spread | stink_bid | liquidity_sniper.",
    )
    side: Mapped[str] = mapped_column(
        String(5), nullable=False,
        comment="YES or NO.",
    )
    target_price: Mapped[float] = mapped_column(Float, nullable=False)
    size_usd: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(
        Float, nullable=False, default=1.0,
        comment="Strategy confidence score in [0, 1].",
    )
    bid_at_signal: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        comment="Best bid at the moment the signal was generated.",
    )
    ask_at_signal: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        comment="Best ask at the moment the signal was generated.",
    )
    params: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict,
        comment="Strategy-specific parameters snapshot at signal creation time.",
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="pending", index=True,
        comment="pending | executed | expired | rejected.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW, index=True,
    )

    # Relationships
    market: Mapped[Market] = relationship("Market", back_populates="signals")
    paper_orders: Mapped[list[PaperOrder]] = relationship(
        "PaperOrder", back_populates="signal"
    )

    def __repr__(self) -> str:
        return (
            f"<Signal id={self.id} strategy={self.strategy!r} "
            f"side={self.side!r} price={self.target_price} status={self.status!r}>"
        )


# ---------------------------------------------------------------------------
# 5. Paper Orders
# ---------------------------------------------------------------------------


class PaperOrder(Base):
    """A simulated limit order created from an approved :class:`Signal`.

    The order_manager monitors open orders against :class:`ObservedTrade` data
    and simulates a fill when a real trade occurs at or better than the target
    price.
    """

    __tablename__ = "paper_orders"
    __table_args__ = (
        Index("ix_po_market_status", "market_id", "status"),
        Index("ix_po_placed_at", "placed_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    signal_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("signals.id", ondelete="SET NULL"), nullable=True, index=True,
    )
    market_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("markets.id", ondelete="CASCADE"), nullable=False, index=True,
    )
    strategy: Mapped[str] = mapped_column(String(50), nullable=False)
    side: Mapped[str] = mapped_column(
        String(5), nullable=False,
        comment="YES or NO.",
    )
    order_type: Mapped[str] = mapped_column(
        String(10), nullable=False, default="limit",
    )
    target_price: Mapped[float] = mapped_column(Float, nullable=False)
    size_usd: Mapped[float] = mapped_column(Float, nullable=False)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="open", index=True,
        comment="open | filled | partially_filled | cancelled | expired.",
    )
    placed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW,
    )
    filled_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    fill_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    fill_size_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    cancel_reason: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Relationships
    signal: Mapped[Signal | None] = relationship("Signal", back_populates="paper_orders")
    market: Mapped[Market] = relationship("Market", back_populates="paper_orders")

    def __repr__(self) -> str:
        return (
            f"<PaperOrder id={self.id} strategy={self.strategy!r} "
            f"side={self.side!r} price={self.target_price} status={self.status!r}>"
        )


# ---------------------------------------------------------------------------
# 6. Positions
# ---------------------------------------------------------------------------


class Position(Base):
    """An open or closed position aggregated from filled :class:`PaperOrder` rows.

    Tracks the full lifecycle from entry to exit, including P&L calculation
    (gross, fees, net).
    """

    __tablename__ = "positions"
    __table_args__ = (
        Index("ix_positions_market_strategy", "market_id", "strategy"),
        # status index auto-created by index=True on column
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    market_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("markets.id", ondelete="CASCADE"), nullable=False, index=True,
    )
    strategy: Mapped[str] = mapped_column(String(50), nullable=False)
    side: Mapped[str] = mapped_column(
        String(5), nullable=False,
        comment="YES or NO.",
    )
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    size_usd: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="Original capital deployed in USD.",
    )
    shares: Mapped[float] = mapped_column(
        Float, nullable=False,
        comment="Number of outcome shares purchased (size_usd / entry_price).",
    )
    status: Mapped[str] = mapped_column(
        String(10), nullable=False, default="open", index=True,
        comment="open | closed.",
    )
    opened_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW, index=True,
    )
    closed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    exit_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    exit_reason: Mapped[str | None] = mapped_column(
        String(50), nullable=True,
        comment="resolution | target_hit | stop_loss | manual | expired.",
    )
    gross_pnl: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        comment="(exit_price - entry_price) * shares.",
    )
    fees: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        comment="Estimated fees (Polymarket charges ~2% taker fee).",
    )
    net_pnl: Mapped[float | None] = mapped_column(
        Float, nullable=True,
        comment="gross_pnl - fees.",
    )

    # Relationships
    market: Mapped[Market] = relationship("Market", back_populates="positions")

    def __repr__(self) -> str:
        return (
            f"<Position id={self.id} strategy={self.strategy!r} "
            f"side={self.side!r} status={self.status!r} net_pnl={self.net_pnl}>"
        )


# ---------------------------------------------------------------------------
# 7. Price Snapshots
# ---------------------------------------------------------------------------


class PriceSnapshot(Base):
    """Spot price of a tracked crypto asset at 1-minute granularity.

    Sourced from CoinGecko or Binance and used by strategy evaluation and
    the risk manager.  Data is also cached in Redis for fast reads.
    """

    __tablename__ = "price_snapshots"
    __table_args__ = (
        Index("ix_ps_crypto_ts", "crypto", "timestamp"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    crypto: Mapped[str] = mapped_column(
        String(10), nullable=False, index=True,
        comment="BTC, ETH, or SOL.",
    )
    price_usd: Mapped[float] = mapped_column(Float, nullable=False)
    source: Mapped[str] = mapped_column(
        String(20), nullable=False,
        comment="coingecko | binance.",
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True,
    )

    def __repr__(self) -> str:
        return (
            f"<PriceSnapshot id={self.id} crypto={self.crypto} "
            f"price={self.price_usd} source={self.source!r}>"
        )


# ---------------------------------------------------------------------------
# 8. System State
# ---------------------------------------------------------------------------


class SystemState(Base):
    """Key/value store for persisting runtime engine state across restarts.

    Examples: last scan timestamp, daily P&L accumulator, kill-switch state.
    Values are stored as JSONB to accommodate arbitrary data shapes.
    """

    __tablename__ = "system_state"

    key: Mapped[str] = mapped_column(
        String(100), primary_key=True,
        comment="Unique state key, e.g. 'last_scan_at', 'daily_pnl'.",
    )
    value: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict,
        comment="Arbitrary JSON payload.",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW, onupdate=_NOW,
    )

    def __repr__(self) -> str:
        return f"<SystemState key={self.key!r}>"


# ---------------------------------------------------------------------------
# 9. Strategy Configs
# ---------------------------------------------------------------------------


class StrategyConfig(Base):
    """Persisted per-strategy, per-market parameter overrides.

    Hierarchy:
    * ``market_id=None AND crypto=None`` — global default for the strategy
    * ``market_id=None AND crypto='BTC'`` — default for all BTC markets
    * ``market_id=<id>`` — override for a specific market

    The engine resolves the most specific config when evaluating a market.
    """

    __tablename__ = "strategy_configs"
    __table_args__ = (
        Index("ix_sc_strategy_market", "strategy", "market_id"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    strategy: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True,
        comment="Strategy name: volatility_spread | stink_bid | liquidity_sniper.",
    )
    market_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("markets.id", ondelete="CASCADE"), nullable=True, index=True,
        comment="NULL = applies to all markets (default).",
    )
    crypto: Mapped[str | None] = mapped_column(
        String(10), nullable=True,
        comment="NULL = applies to all cryptos.",
    )
    enabled: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True,
        comment="Whether this strategy is active for the given scope.",
    )
    params: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict,
        comment="Strategy-specific parameter overrides.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=_NOW, onupdate=_NOW,
    )

    # Relationships
    market: Mapped[Market | None] = relationship(
        "Market", back_populates="strategy_configs"
    )

    def __repr__(self) -> str:
        return (
            f"<StrategyConfig id={self.id} strategy={self.strategy!r} "
            f"market_id={self.market_id} enabled={self.enabled}>"
        )
